version: "3.9"
services:
  api:
    image: python
    env_file: .env
    volumes:
      - ./app:/app
    command: >
      bash -c "
        cd app
        pip install -r requirements.txt
        python main.py
      "
