version: "3.9"
services:
  test_name:
    image: ${PROJECT_NAME}/test_service
    build:
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      # NOTE: To provide files
      - type: bind
        source: test.json
        target: /test.json
